name: Configuration Assistant
id: ConfigAssistant
key: ConfigAssistant
author_link: http://openmelody.org/
author_name: "Byrne Reese, Open Melody Software Group"
description: This plugin provides a simple YAML based framework for creating plugin and theme configuration options.
version: 2.2.6
static_version: 15
schema_version: 3

object_types:
  blog:
    selected_config: string meta

upgrade_functions:
  static_copy:
    # A version_limit is required to trigger the upgrade function. So, just
    # use a way big one, just so I don't have to remember to update it.
    version_limit: 999
    handler: $ConfigAssistant::ConfigAssistant::Static::upgrade

init_app: $ConfigAssistant::ConfigAssistant::Init::init_app

callbacks:
  MT::App::CMS::template_param.cfg_plugin:  $ConfigAssistant::ConfigAssistant::Plugin::xfrm_cfg_plugin_param
  MT::App::CMS::template_source.cfg_plugin: $ConfigAssistant::ConfigAssistant::Plugin::xfrm_cfg_plugin
  blog_template_set_change:                 $ConfigAssistant::ConfigAssistant::Prefs::on_template_set_change

config_settings:
  PluginStaticVersion:
    type: 'HASH'

applications:
  cms:
    menus: $ConfigAssistant::ConfigAssistant::Init::update_menus
    methods:
      theme_options:    $ConfigAssistant::ConfigAssistant::Plugin::theme_options
      ca_config_entry:  $ConfigAssistant::ConfigAssistant::Plugin::list_entry_mini
      ca_select_entry:  $ConfigAssistant::ConfigAssistant::Plugin::select_entry
      ca_config_entry_or_page:  $ConfigAssistant::ConfigAssistant::Plugin::list_entry_or_page
      ca_select_entry_or_page:  $ConfigAssistant::ConfigAssistant::Plugin::select_entry_or_page
      ca_select_author: $ConfigAssistant::ConfigAssistant::Plugin::select_author
      ca_save_config:   $ConfigAssistant::ConfigAssistant::Plugin::save_config
      run_static_copy:  $ConfigAssistant::ConfigAssistant::Static::manual_run
      ca_prefs_apply:   $ConfigAssistant::ConfigAssistant::Prefs::apply
      ca_prefs_chooser: $ConfigAssistant::ConfigAssistant::Prefs::chooser
    search_apis:
      entry:
        setup_terms_args: $ConfigAssistant::ConfigAssistant::Plugin::entry_search_api_prep

config_types:
  author:
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_author
  blogs:
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_blogs
  category:
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_category
  category_list:
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_category_list
  checkbox: 
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_checkbox
  colorpicker: 
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_colorpicker
  datetime:
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_datetime
  entry:
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_entry
  entry_or_page:
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_entry_or_page
  file: 
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_file
  folder:
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_folder
  folder_list:
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_folder_list
  link-group:
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_link_group
  page:
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_page
  radio-image:
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_radio_image
  radio: 
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_radio
  select: 
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_select
  tagged-entry:
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_tagged_entry
  text-group:
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_text_group
  text: 
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_text
  textarea:
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_textarea

blog_preferences:
  __default__:
    label: 'Factory Default'
    description: 'These are the default factory settings for Melody.'
    order: 1
    preferences: default_prefs.yaml
